version: '3.9'

services:

  web:
    build: ./app
    ports:
      - "8008:8000"
    command: python3 main.py
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U salarybot_secure_user -d salarybot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - db

#  redis:
#    build:
#      context: redis
#    image: myredis
#    restart: always
#    privileged: true
#    command: sh -c "./init.sh"
#    env_file:
#      - .env
#    volumes:
#      - redis_data:/data:r

volumes:
  postgres:
  pgadmin:
#  redis_data: